spring.application.name=backend
server.port=8082

# ----------------------------
# DATABASE CONFIGURATION
# ----------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/hotel_booking
spring.datasource.username=postgres
spring.datasource.password=11072004

# Driver postgresql
spring.datasource.driver-class-name=org.postgresql.Driver

# ----------------------------
# JPA / HIBERNATE CONFIG
# ----------------------------

# Automatically create entities based on tables (update/create/drop)
spring.jpa.hibernate.ddl-auto=update

# Print SQL statement when run (debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true
spring.datasource.hikari.maximum-pool-size=10

# Enable logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.security=DEBUG
logging.level.com.hotelbookingsystem=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

# Secret to sign JWT
jwt.secret=aj83j2ns8dhf9s82hf72js0fh92jhf0293hfs82hf82hsf8h2fhs82hf==
jwt.expiration=3600000

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hoangquyle11@gmail.com
spring.mail.password=btnm mwld irue lszm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from=hoangquyle11@gmail.com
frontend.reset-password-url=http://localhost:3000/reset-password

